export const ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  CONFLICT: "CONFLICT",
  BAD_REQUEST: "BAD_REQUEST",
  BAD_GATEWAY: "BAD_GATEWAY",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",

  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_INVALID_ACCESS_TOKEN: "AUTH_INVALID_ACCESS_TOKEN",
  AUTH_INVALID_REFRESH_TOKEN: "AUTH_INVALID_REFRESH_TOKEN",
  AUTH_REFRESH_TOKEN_SUBJECT_MISMATCH: "AUTH_REFRESH_TOKEN_SUBJECT_MISMATCH",
  AUTH_INVALID_OAUTH_STATE: "AUTH_INVALID_OAUTH_STATE",

  CONFIG_INVALID_DURATION: "CONFIG_INVALID_DURATION",

  OAUTH_GOOGLE_TOKEN_EXCHANGE_FAILED: "OAUTH_GOOGLE_TOKEN_EXCHANGE_FAILED",
  OAUTH_GOOGLE_USERINFO_FAILED: "OAUTH_GOOGLE_USERINFO_FAILED",
  OAUTH_GITHUB_TOKEN_EXCHANGE_FAILED: "OAUTH_GITHUB_TOKEN_EXCHANGE_FAILED",
  OAUTH_GITHUB_USERINFO_FAILED: "OAUTH_GITHUB_USERINFO_FAILED",
  OAUTH_GITHUB_EMAILS_FAILED: "OAUTH_GITHUB_EMAILS_FAILED",

  QUESTION_INVALID_CORRECT_OPTION_INDEX: "QUESTION_INVALID_CORRECT_OPTION_INDEX",
  QUESTION_DUPLICATE_REPORT: "QUESTION_DUPLICATE_REPORT",
  QUIZ_DUPLICATE_QUESTION_IDS: "QUIZ_DUPLICATE_QUESTION_IDS",
  QUIZ_UNKNOWN_QUESTION_IDS: "QUIZ_UNKNOWN_QUESTION_IDS",
  QUIZ_HAS_UNAPPROVED_QUESTIONS: "QUIZ_HAS_UNAPPROVED_QUESTIONS",
  QUIZ_NO_AVAILABLE_QUESTIONS: "QUIZ_NO_AVAILABLE_QUESTIONS",
  QUIZ_DUPLICATE_ANSWERS: "QUIZ_DUPLICATE_ANSWERS",
  QUIZ_ANSWER_OUT_OF_SCOPE: "QUIZ_ANSWER_OUT_OF_SCOPE",
  QUIZ_INCOMPLETE_ANSWERS: "QUIZ_INCOMPLETE_ANSWERS",
  QUIZ_INVALID_OPTION_INDEX: "QUIZ_INVALID_OPTION_INDEX",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
